### ISSUE TITLE
Impossible to upload cell_label.tsv and cell_label_colors.tsv

### ISSUE THREAD

**Issue by charles-bernard** [pinellolab/STREAM#1]
Hi,

As a user of ElPiGraph, i wanted to try your online tool because I was curious to see how well it would work with your MLLE dimRed method and with your LOESS feature selection. And the answer is that it works amazingly well and that the stream output was consistent with my previous findings. However, I found out that it was impossible for me to upload the cell_label and the cell_label_colors files on the online application. I have of course checked that the format of these files satisfied all the conditions you have written in the Readme. Perhaps it's just a small omission in the code of your wrapper...

Anyway, let me know when these uploads will be available, so that I can visualize the distribution of my clusters on your beautiful stream plots ;)

Best,

Charles

**Comment by lucapinello** [comment]
Hey Charles,

Do you mind to share the all the files you were using?

Happy to take a look,

Luca

**Comment by charles-bernard** [comment]
Hi Luca,

Thank you for your super quick reply ! And thank you for proposing me your help, that's really nice of you.

I personally don't mind but I don't know if the people who where involved in the production of these data do. Sorry for that. Nevertheless, what I can share with you is the expression matrix filled with 0 values, as well as the labels and their corresponding colors. Hope it is ok for you?

[cell_labels.tsv.gz](https://github.com/pinellolab/STREAM/files/1955670/cell_labels.tsv.gz)
[cell_labels_colors.tsv.gz](https://github.com/pinellolab/STREAM/files/1955671/cell_labels_colors.tsv.gz)
[hvg_expr_mat.tsv.gz](https://github.com/pinellolab/STREAM/files/1955672/hvg_expr_mat.tsv.gz)

Ps: On another note, I would be interested in retrieving the cell coordinates on the MLLE embedding to plot them back with the R rgl package. Unfortunately, the way the cells are ordered in the output coord_cells.csv is not the same as in the input expression matrix. Would it be therefore possible to return the cell names as well in the coord_cells table ?

Thank you so much,

Charles

**Comment by huidongchen** [comment]
Hi, Charles, 

Thanks for trying STREAM and your feedbacks!  We just fixed it! It should work now.

The issue was caused by our recent update, in which the filename was changed by mistake when uploading them. (Also for the Hex color, **we currently only support 6 digits**. We noticed that in your example color file, you are using 8 digits. You might need to change that)

Please let us know if you encounter any other issues. Thanks!

Best,
Huidong

**Comment by charles-bernard** [comment]
Awesome !

Thank you very much Huidong, it works like a charm now !

Concerning the output coord_cells.csv file, can you tell me how I can know to which cell does a line correspond to? Thanks to the first column, I can know the color of the cell, but what if I'd like to know its identity?

Best,

Charles

**Comment by huidongchen** [comment]
Hi, Charles,

I'm happy that it works for you!

In order to avoid some visual artifacts caused by the plotting order of cells, we always shuffle cells before plotting them. Here coord_cells.csv is coordinates of shuffled cells so it's hard to link it to the 'cell_info.tsv' file.

The easiest way to obtain cells' MLLE coordinates and branch ids(line) would be utilizing the precomputed variable files:

>import pandas as pd
>import cPickle
>f = open('./Precomputed/df_flat_tree.pickle', 'rb')
>df_flat_tree = cPickle.load(f)
>f.close()
>f = open('./Precomputed/dict_node_state.pickle', 'rb')
>dict_node_state = cPickle.load(f)
>f.close()

The column '**X_projected**' and '**branch_id**' in **df_flat_tree** contain MLLE coordinates and branch ids respectively. **dict_node_state** has node labels.

I hope the above is useful to you. In the meantime, if it solves your concern, would you mind closing this issue? Thanks!

Best,
Huidong

**Comment by charles-bernard** [comment]
Awesome! Thank you for your help!

I'm going to close this issue now.

Best,
Charles
