### ISSUE TITLE
rpy2.rinterface.RRuntimeError

### ISSUE THREAD

**Issue by zhumengyan** [pinellolab/STREAM#18]
Hello,
Thanks for amazing tools.
I use STREAM in anaconda (v0.3.9).
my command is: 
`stream -m RD001_res0.6_T_scaled.tsv -l RD001_res0.6_T_label.tsv --lle_components 4 --EPG_shift --umap`
RD001_res0.6_T_scaled.tsv contains expression profile scaled by Seurat V3, and RD001_res0.6_T_label.tsv contains cluster label.

However, I got this error:
rpy2.rinterface.RRuntimeError: Error in igraph::add.edges(graph = Net, edges = as.vector(rbind(NewBR,  :
  At type_indexededgelist.c:269 : invalid (odd) length of edges vector, Invalid edge vector

AND if I remove --EPG_shift, I got another error:
TypeError: fruchterman_reingold_layout() got an unexpected keyword argument 'random_state'

Do you know what I can do to fix it ?

Mengyan Zhu

**Comment by huidongchen** [comment]
Hi Mengyan,

Thanks for trying STREAM. For the first error, it’s indeed a bug caused by the parameter ‘EPG_shift’. We are aware that this may happen in some extreme cases and will fix it in the future. I would suggest removing the parameter ‘—EPG_shift’ for now.

For the second error, it’s caused by the incompatible version of python package ‘ networkx’. I assume you didn’t install ‘stream’ in a newly created environment. Re-installing the version 2.1 via ‘conda install networkx=2.1’ should solve the issue.

**Comment by zhumengyan** [comment]
Thanks for your reply.
I have solved the problem after following your advice. 

1. after removing parameter "--EPG_shift" , `rpy2.rinterface.RRuntimeError` is gone. 
2. networkx version in conda is 2.1 and its version in built-in python is 2.3. Strangely, `networkx.__version__` is 2.1 in conda environment, but version of networkx is 2.3 in ipython. Finally I remove networkx in built-in python. `TypeError: fruchterman_reingold_layout()` is gone.

**Comment by huidongchen** [comment]
Awesome! Glad it helps! :)
