### ISSUE TITLE
no output for TG, DE, LG

### ISSUE THREAD

**Issue by yangithub33** [pinellolab/STREAM#22]
Hello Huidong,
I am trying to get TG (or DE,or LG). but I got the folder "transition_genes" generated, but nothing in there. here is the command:
/bin/stream -m matrix.tsv.gz -l cell_label.tsv.gz -c cell_label_Color.tsv.gz -g genelist106.txt --TG -r S0 -p -o output_stream
the run message as below, it seems not finished.
Importing the precomputed pkl file...
Saving results in: output_stream
Identifying transition genes...
Minimum number of cells expressing genes: 31

it will be greatly appreciated if you could help me out.
Thanks,
Ting

**Comment by huidongchen** [comment]
Hi Ting,

Based on the output information, since there is no error shown, it seems that the command line is still running and it's not finished yet. Overall the marker gene detection part is a bit time-consuming. How long has it been running?  I'm wondering if it's completed eventually.

**Comment by OpenIDUser6** [comment]
I submitted job on cluster. when I found the job stopped, then I checked the output, no files were generated, then I check the .e file and I did not see error message. do you think this is memory issue?
Thanks,
Tingfen

**Comment by huidongchen** [comment]
Hi Tingfen,

I assume you have a large number of cells. The script probably quit due to the memory issue.

There are two ways you can potentially try :

* If you are running STREAM command line, you can try to lower the parameter `--lle_neighbours` (percentage of neighbors). You can set it to 30.0/the number of your cells. 

* Since STREAM command line is a simplified version of STREAM bioconda package, it does not support all the functions available in STREAM python package. If you are running your custom python script based on https://github.com/pinellolab/STREAM#tutorial, you can have more options to optimize your script. E.g. changing the default dimension method step to `st.dimension_reduction(adata, method ='se', nb_pct=30.0/the number of your cells)`

The above two functions will significant speed up STREAM analysis and also make it more scalable.

**Comment by OpenIDUser6** [comment]
Hi Huidong,
I did took you suggestion by using st.dimension_reduction(adata, method ='se', nb_pct=30.0/the number of your cells), I was able to generate trajectory. My problem is that I could not get any of --DE --TG --LG working. 
Any suggestions will be greatly appreciated.
Tingfen

**Comment by huidongchen** [comment]
are you running STREAM command line or STREAM python script ? Since `st.dimension_reduction(adata, method ='se', nb_pct=30.0/the number of your cells)` is meant for STREAM python script while `--DE --TG --LG ` is for STREAM command line.

If you are using STREAM command line, what's the last output file you saw?

**Comment by OpenIDUser6** [comment]
I am running python command line,
1) first, I add method='se' to st.dimension_reduction (as:st.dimension_reduction(adata, method ='se'))  in anaconda3/pkgs/stream-0.3.9-py37r351h1c2f66e_0/lib/python3.7/site-packages/stream/command_line.py.
2)Then, I ran as: 
stream --lle_neighbours 0.005 -m matrix.tsv.gz --log2 --norm -l cell_label.tsv.gz -c cell_label_Color.tsv.gz -g genelist106.txt -s all -o output_stream
 this step worked
3)third, when I tried to do --DE or TG, or LG, none of them worked using -p (precalculated)
 stream --lle_neighbours 0.005 -m matrix.tsv.gz --log2 --norm -l cell_label.tsv.gz -c cell_label_Color.tsv.gz -g genelist106.txt  --TG -p -o output_stream
 the run stopped after about 10 or 20 mins, the output as:
"Importing the precomputed pkl file...
Saving results in: output_stream
Identifying transition genes...
Minimum number of cells expressing genes: 31"

I checked the job summary file: I gave 72G memory, it stopped at max_vmem 120G, when I gave 180G, it stopped at max_vmem 340G. 
I found out there is option of n_processes, I tried to give 8, still did not work.
any suggestions?
Tingfen

**Comment by huidongchen** [comment]
Can you check if the genes names are unique? I assume it might be related to the repetitive gene names (Please see #14)

**Comment by huidongchen** [comment]
Hi Tingfen, if I understand correctly, you are able to get the transition gene tsv files but failed to plot them? It looks relevant to the previous opened issue #20 . I'm not sure if the solution posted would be helpful to you. Unfortunately I didn't encounter the error myself. If you could provide more details to reproduce the error, I'm more than happy to look into it.
