### ISSUE TITLE
Bioconda channels not available

### ISSUE THREAD

**Issue by xyang2uchicago** [pinellolab/STREAM#29]
I am creating conda virtualenv as suggested in the readme file
conda create -n myenv python=3.6 stream jupyter

but I got the following errors: 
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - stream

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by lucapinello** [comment]
You probably skipped some required steps:

Installation with Bioconda (Recommended)

   1.

   If Anaconda (or miniconda) is already installed with Python 3, skip to
   2) otherwise please download and install Python3 Anaconda from here:
   https://www.anaconda.com/download/
   2.

   Open a terminal and add the Bioconda channel with the following commands:

$ conda config --add channels defaults
$ conda config --add channels bioconda
$ conda config --add channels conda-forge


   1. Create an environment named myenv , install stream, jupyter, and
   activate it with the following commands:


   - *For single cell RNA-seq analysis*:

$ conda create -n myenv python=3.6 stream jupyter
$ conda activate myenv

**Comment by xyang2uchicago** [comment]
Thanks! Sorry I skipped config step.

Also, this is not

**Comment by meichendong** [comment]
Hi,
I'm trying to download stream to my windows PC and I kept getting the error:
`(base) PS C:\Users\meichen> conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
(base) PS C:\Users\meichen> conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
(base) PS C:\Users\meichen> conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(base) PS C:\Users\meichen> conda create -n myenv python stream jupyter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - stream

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

Could you please help me to resolve this?
Thanks!

**Comment by lucapinello** [comment]
Unfortunately Stream is not available on windows using conda. However you
can consider using the docker version.
