### ISSUE TITLE
STREAM working environment

### ISSUE THREAD

**Issue by xyang2uchicago** [pinellolab/STREAM#31]
I am trying to install STREAM in a Linux server. On the server, I have a /home/myhome/ directory which has limited space and memory. I also have a lab-share/ directory where I want to install STREAM.

Now, the command **_$ conda info_** gives the following information:

       package cache : lab-share/stream_2019/.conda/pkgs
       envs directories : /home/myhome/.conda/envs
                          /apps/software/gcc-6.2.0/miniconda3/4.7.10/envs
      platform : linux-64

My questiosn are:
Q1) Should I change the 'envs directories ?'
Q2) If yes, how?

Thanks,
Holly

**Comment by huidongchen** [comment]
Hi Holly,
If you have miniconda installed, you should be able to create a new env following https://github.com/pinellolab/STREAM#installation-with-bioconda-recommended. I'm not sure why you want to change the env directory. 

I guess what you are saying is more related to the installation of anaconda instead of STREAM package.
