### ISSUE TITLE
LOESS issue

### ISSUE THREAD

**Issue by ateissan** [pinellolab/STREAM#33]
When I am running stream using python (after bioconda install) or using jupyter, I have n issue when I try to select variable genes:

>>> st.select_variable_genes(adata,loess_frac=0.01)
/data/users/ateissan/.conda/envs/stream/lib/python3.6/site-packages/statsmodels/nonparametric/smoothers_lowess.py:165: RuntimeWarning: invalid value encountered in true_divide
  res = _lowess(y, x, frac=frac, it=it, delta=delta)
/data/users/ateissan/.conda/envs/stream/lib/python3.6/site-packages/statsmodels/nonparametric/smoothers_lowess.py:165: RuntimeWarning: invalid value encountered in greater_equal
  res = _lowess(y, x, frac=frac, it=it, delta=delta)
st.select_variable_genes?
/data/users/ateissan/.conda/envs/stream/lib/python3.6/site-packages/stream/core.py:452: RuntimeWarning: invalid value encountered in less
  mat_sign[np.where(residuals<0)[0]] = -1
/data/users/ateissan/.conda/envs/stream/lib/python3.6/site-packages/stream/core.py:457: RuntimeWarning: invalid value encountered in less_equal
  id_non_var_genes = np.where(residuals<=cutoff)[0]
0 variable genes are selected

Thanks for your help,
Aurélie

**Comment by huidongchen** [comment]
Hi Aurélie,

Did you start from the raw count matrix? If so, did you perform the normalization(`st.normalize_per_cell(adata)`) and log transformation(`st.log_transform(adata)`)?

**Comment by ateissan** [comment]
Yes, I have the raw count matrix with normalization and log transformation. I did a filtering on genes and now it's working. 
However, I was wondering if we can do clustering and define cell-type with STREAM? Because, I have no clue on the cell type that are present in my dataset. And so I have no cell label.

**Comment by ateissan** [comment]
And after that can I select specific cell types (or clusters) to reconstruct trajectory just on a subset of cells?

**Comment by huidongchen** [comment]
> Yes, I have the raw count matrix with normalization and log transformation. I did a filtering on genes and now it's working.
> However, I was wondering if we can do clustering and define cell-type with STREAM? Because, I have no clue on the cell type that are present in my dataset. And so I have no cell label.

Yeah, that's a good question. That's something on our to-do list but unfortunately it's not implemented yet. Also cell-type annotation is another big field and there are already quite a few methods out there. 

To get the labels, one simple way would be performing clustering analysis using other tools (scanpy or seurat) and export the obtained cluster labels to STREAM. Or you can also run other single cell type annotation analysis tool to get the cell type labels. But another independent analysis has to be done in order to get the cell labels for STREAM analysis (Meanwhile they can also serve as a validation of STREAM analysis).

**Comment by huidongchen** [comment]
> And after that can I select specific cell types (or clusters) to reconstruct trajectory just on a subset of cells?

Yes, you can. You can do something like `adata = adata[adata.obs['label']=='your_celltype']` to subset the cells.
