### ISSUE TITLE
stream plot of mapped cells and related gene expression

### ISSUE THREAD

**Issue by ccshao** [pinellolab/STREAM#34]
Many thanks for the nice tool and we get some interesting results!

One issue that we are not sure is how to explain the width of mapped data in the stream plot, both on mapping and gene expression.

For exmaple, the stream plot of  reference data look likes the below. One branch is highlighted.
![f0](https://user-images.githubusercontent.com/4980631/66211332-27f33080-e6bc-11e9-9ab2-957ba14e497d.png)

Then we mapped the perturbation data and plotted the data. Now the highlighted braches is **stretched along the pesudotime**, see the gray area in the highlighted regions.
```
st.map_new_data(adata1, adata2, method="umap")
st.stream_plot(adata1, adata_new=adata2, show_all_colors=False, root='S5', fig_legend_ncol=6, fig_size=(8,8), save_fig=True)
```
![f1](https://user-images.githubusercontent.com/4980631/66211596-ab148680-e6bc-11e9-9622-7c62fa94098b.png)

To get the stream of the adata2, we used
```
st.stream_plot(adata2, root='S5', fig_legend_ncol=6, fig_size=(8,8), save_fig=True, fig_name='stream2.pdf')
```

![f2](https://user-images.githubusercontent.com/4980631/66211772-f9298a00-e6bc-11e9-9e95-2ae49aa23992.png)

**The width of stream plot of adata2 is much narrower than the reference (see the first figure).**

Next we plot the gene expression
```
st.stream_plot_gene(adata1, root='S5', genes=genes, save_fig=True)
st.stream_plot_gene(adata2, root='S5', genes=genes, save_fig=True)
```
![f4](https://user-images.githubusercontent.com/4980631/66211884-32fa9080-e6bd-11e9-8ffc-a0736e03aee3.png)

**The width of stream plot of adata2 is clearly narrow than adata1.** Actually adata2 have around 10% more cells that adata1, but it is not reflected on the width of the stream plot

We would like to show that the cells are differently distributed in adata1 and adata2, so is the 
gene profile. With the commands I used above, the stream plots seem not comparable between these datasets. 

My questions are:
1. how to get a nice stream plot of adata2 (mapped data) while the width is comparable to adata1 (ref data)
2. related, how to make the gene plot comparable between adata1 and adata2

Interestingly, stream_plot_genes has an argument "adata_new" but not working
```
Signature:
st.stream_plot_gene(
    adata,
    genes=None,
    percentile_expr=95,
    root='S0',
    factor_num_win=10,
    factor_min_win=2.0,
    factor_width=2.5,
    flag_log_view=False,
    factor_zoomin=100.0,
    preference=None,
    save_fig=False,
    fig_path=None,
    fig_size=(12, 8),
    fig_format='pdf',
    tick_fontsize=20,
    label_fontsize=25,
)
Docstring:
Generate stream plots of genes

Parameters
----------
adata: AnnData
    Annotated data matrix.
adata_new: AnnData
    Annotated data matrix for new data (to be mapped).

```

**Comment by huidongchen** [comment]
Hi Chunxuan,

Thanks for trying STREAM and I'm glad to know STREAM is being helpful in your research. These are both very important points. I would try to explain as best as I can.

1) The width of STREAM branches indicates the relative abundance (i.e. the ratio) of cells between branches. Since the absolute number of cells in each branch needs to be scaled based on the total number of cells within the same STREAM plot, it might not be fair to compare the widths across different STREAM plots (The width is proportional to the number of cells within the same plot, but it's not the exact number of cells). A potential way to increase the widths of branches is to lower the factor `factor_width`(This is the ratio of stream plot length to stream plot width. So for the same length, the smaller `factor_width` is, the bigger the width is. But this will increase the widths of all branches and won't dramatically increase the widths).

2) You are totally right. We don't have STREAM gene plot for mapped data. One important concern we have is that for STREAM gene plot, the gene expression pattern is the average expression of all cells within each sliding window. That being so, when visualizing the gene expressions of mapped cells, they will be averaged by the reference cells. So it won't be helpful for users to study the expression pattern of mapped cells. So I would suggest using subway map plot to visualize genes of mapped cells `st.subwaymap_plot_gene(adata1,adata_new=adata_new2, your_gene_list, show_all_cells=False` . But if you don't care about the gene expression patterns of mapped cells and only wanna visualize both ref cells and mapped cells together, here is a quick workaround:
```
import anndata as ad
import numpy as np
import pandas as pd

adata_merged = adata.concatenate(adata_new,index_unique=None)
adata_merged.uns = adata.uns
adata_merged.uns['label_color'].update(adata_new.uns['label_color'])
for x in adata.obsm_keys():
    if(x in adata_new.obsm_keys()):
        adata_merged.obsm[x] = np.vstack((adata.obsm[x],adata_new.obsm[x]))
adata_merged.raw = ad.AnnData(pd.DataFrame(index=adata_merged.obs_names,
                                           columns=adata.raw.var_names,
                                           data=np.vstack((adata.raw.X,adata_new.raw.X))))
st.stream_plot_gene(adata_merged, genes=your_gene_list) 
```
This will give you STREAM gene plot of the merged ref and mapped cells.

Hope the above is helpful to you.

**Comment by ccshao** [comment]
@huidongchen thanks very much for the details! I have tried your suggestions and here are a few updates. I hope these won't bother you too much.

### merged gene plots

I tried the kindly provided codes and interestingly the stream gene plot used the layout identical to the one produced by  `st.stream_plot(adata1, adata_new=adata2, ...)`

An example is showed below. 

![Screenshot from 2019-10-09 16-22-38](https://user-images.githubusercontent.com/4980631/66490506-9156b300-eab1-11e9-8b50-3911cd864385.png)

Further, could  **two different color schemes** be used for the expression value to indicate the **cell origins** (e.g., blue-white gradient for adata1 and red-white gradient for adata2)? That will be perfect for us. I am not family with python so a litte of instruction are really appreciated!

### stream layout with/without adata_new

Here is a tricky issue. I noticed there are two slight different layouts for the same adata1, which contains the refernce cells. The first stream layout is produced by **standard pipeline st.stream_plot(adata1)**. Let it be **layout_1**, and second stream layout is the produced with the **map fuction st.stream_plot(adata1, adata_new=adata2),** be **layout_2**, the grey stream. The princle struction is identical but the end shape is different. see blow (grey is reference). Do you have some ideas on where the diffrences come from?

![Untitled 1](https://user-images.githubusercontent.com/4980631/66492481-c57fa300-eab4-11e9-88fe-9e6e8c39c684.png)

Actually I want to use the grey stream for the adata1. If  I plot the genes with `st.stream_plot_gene(adata, ...)`,  the **layout_1** is used.  How do I get stream gene plot use the grey part in **layout_2  for adata1**? Interestingly with your codes, as shown in the first figure, the adata1 indeed use the grey part, just together with adata2. With two plots separataly for adata1 and adata2 using layouts extracted from **layout_2**,  the width of branches seem comparable as they come form one stream originally.


### slicding window

> One important concern we have is that for STREAM gene plot, the gene expression pattern is the average expression of all cells within each sliding window. That being so, when visualizing the gene expressions of mapped cells, they will be averaged by the reference cells. So it won't be helpful for users to study the expression pattern of mapped cells. 

I guess that the mapped cells will use the pseudotime of reference cells, and the genes of mapped cell will be averaged in the same way as in the reference (with the same sliding windown used refernce). Why in the case the stream genes plot of mapped data is not helpful and subway plot is better? For us the subway plots are fuzzy and stream plot is much more intuitive.

**Comment by huidongchen** [comment]
>I tried the kindly provided codes and interestingly the stream gene plot used the layout identical to the one produced by st.stream_plot(adata1, adata_new=adata2, ...)

This is what we should expect, i.e. the stream gene plot of merged adata objects is identical to st.stream_plot(adata1, adata_new=adata2, ...). because the width of branch represents the proportion of cells. The stream gene plot here is the averaged gene expression pattern of both adata1 and adata2. 

>Further, could two different color schemes be used for the expression value to indicate the cell origins (e.g., blue-white gradient for adata1 and red-white gradient for adata2)? That will be perfect for us. I am not family with python so a litte of instruction are really appreciated!

It's a great idea but unfortunately technically it's not trivial to achieve that. Like I said previously, currently stream gene plot can only visualize the averaged gene expressions of all cell types along the trajectory. It can not visualize the gene expression of one specific cell type.

> Here is a tricky issue. I noticed there are two slight different layouts for the same adata1, which contains the refernce cells. The first stream layout is produced by standard pipeline st.stream_plot(adata1). Let it be layout_1, and second stream layout is the produced with the map fuction st.stream_plot(adata1, adata_new=adata2), be layout_2, the grey stream. The princle struction is identical but the end shape is different. see blow (grey is reference). Do you have some ideas on where the diffrences come from?

The difference between the branch widths may cause confusion but it actually makes sense. One thing to keep in mind is that in STREAM plot, the width is NOT the number of cells. Instead it is the proportions of cells to the total number of cells. When new cells are mapped to ref trajectory, the STREAM plot needs to be re-made (The branching structure, i.e. x axis, will be preserved but the number of cells will be re-counted so the proportion of cells will be further recalculated as well, i.e. y axis). The number of ref cells does not change but its proportion to the two merged datasets changed. That's why the shape looks different.

> I guess that the mapped cells will use the pseudotime of reference cells, and the genes of mapped cell will be averaged in the same way as in the reference (with the same sliding windown used refernce). Why in the case the stream genes plot of mapped data is not helpful and subway plot is better? For us the subway plots are fuzzy and stream plot is much more intuitive.

Because in STREAM gene plot, it CAN NOT distinguish cell types or cell origins (ref cells or mapped cells). That being so, the sliding window will average ref and mapped cells together along the same X axis. So STREAM gene plot can't visualize the gene expression patterns of mapped cells alone, and instead it always visualizes the gene expression patterns of merged and averaged ref and mapped cells. While for subway map lot, it can visualize the gene expressions of ref cells and mapped cells separately.

**Comment by ccshao** [comment]
Thanks very much for being patience with us! We now understand gene plots a lot better, and hope to see more advanced option to color genes and branches.
