### ISSUE TITLE
program quits when the matrix is big  

### ISSUE THREAD

**Issue by fangge-Li** [pinellolab/STREAM#4]
Hi all,
    Thank you for developing "STREAM". I have used STREAM for our data. It works very well when the gene-expression matrix is small.
    Now I want to use STREAM for the new data containing 7465 cells and 8858 genes. And I have allocated 8 cores and 16G memory to Docker container. But the program would quit after printing "Selecting features...", without any error message.
    Please help me to solve this problem.
    Thank you so much!

**Comment by huidongchen** [comment]
Hi, Fangge,

Thanks for trying STREAM.
Would you mind sharing with us the data matrix ? We are happy to take a look.

Best,
Huidong

**Comment by huidongchen** [comment]
@fangge-Li  Sure! Huidong.Chen@MGH.HARVARD.EDU

**Comment by cstill1992** [comment]
Hi,

I was wondering if there was any further update to this issue. I'm running into a similar situation where st.dimension_reduction(data) keeps quiting due to memory constraints (specifically I'm getting feedback that the process has been "killed" after about 2-3 hours of working). I'm working with a large dataset as well, 13230 cells with 10622 genes present (Drop-seq dataset). I'm doing this on a cluster allocating 30 cores and 128G of memory. Any help would be appreciated.

Thanks,
Chris

**Comment by huidongchen** [comment]
Hi Chris @cstill1992 ,

Sorry about the issue. st.dimension_reduction(data) uses 'MLLE' as the default dimension reduction method, which currently is not efficiently implemented yet.

As an alternative solution, you can try 

```
st.dimension_reduction(adata,method='umap', n_components=2)
st.seed_elastic_principal_graph(adata ,clustering='kmeans')
```
Of course you can also increase the `n_components` to get more detailed structure.  

This will speed it up significantly for large dataset.

**Comment by cstill1992** [comment]
Hi Huidong,

Thanks for the quick response. I'll give it a try and let you know how it goes.

Thanks,
Chris

**Comment by cstill1992** [comment]
Hi Huidong,

Thanks for the help. The fix worked nicely.

Best,
Chris

**Comment by huidongchen** [comment]
That’s great! Feel free to let me know if you have any questions.
