### ISSUE TITLE
cell_info.tsv not having all cells

### ISSUE THREAD

**Issue by anjanbharadwaj** [pinellolab/STREAM#5]
Hi,

I was using the command line interface, and was looking through the cell_info.tsv file, but not all of the cells were there (I needed to look at this because I think that file has the true branches for each cell, right?). Is this because the tool is filtering cells (I started with 4000 cells, yet it was filtered to around 450)?

**Comment by huidongchen** [comment]
Hi, 

The cell_info.tsv file should contain the information of **all cells**, including branch id, pseudotime, etc. 

In STREAM pipeline, **we only filter out genes but keep all the cells**. So my guess is that your input matrix might not be appropriate. The input matrix should have **cells in columns and genes in rows**. You might want to transpose your gene expression matrix before feeding it to STREAM. 

Could you please check it?  Thanks!

**Comment by anjanbharadwaj** [comment]
Hi,

I checked the gene expression data, and the cells are in columns and the genes are in rows, so I don't think I need to transpose it. I also tried the following command on another dataset of mine previously, and it worked on that (generated all values in the cell_info). I think the issue I may have been seeing is not that the cell_info.tsv file is filtering data, but rather that when I run the below command, it is only generating the "Precomputed" folder, and no other files/pdfs/etc.

The command is: `docker run -v $PWD:/data -w /data pinellolab/stream STREAM -m mat.tsv -l labels.tsv -s all -o stream_results`. 

Also, another question (this is a bit of a different), but I see that STREAM generates a set of pseudotimes for each possible root branch. Is there any way that STREAM indicates which branch it predicts should be the starting one?

**Comment by anjanbharadwaj** [comment]
Yes, actually the issue seems to be that (what I mentioned in the first paragraph) - when I run the command, it generates the values in "Precomputed", but doesn't create the new cell_info.tsv file. The reason why I thought that the cells were filtered was because I probably first ran it on a small dataset with only 450 cells, and then on the 4000 cell dataset.

**Comment by huidongchen** [comment]
Hi,

Thanks for checking it!

1) That's a good point. But the decision of root node is quite a open challenge. In order to achieve it, currently we have to reply on some exterior information like FACS sorting, marker gene or sampling time. That's why in the default output STREAM gives all the possible trajectories. Sorry that there is no automatic way available in STREAM to determine the root branch. 

2)Yes, cells were actually not filtered out. It was because the analysis didn't get finished. The issue is caused by the memory efficiency issue in current docker image, especially when it comes to large data. We did notice the issue and are working on the new version. We'll keep you posted. In the meantime, can you try increase the memory size in docker (Docker -> Preferences -> Advanced)?

I hope the above is useful to you.

**Comment by anjanbharadwaj** [comment]
Hi,

Thanks for letting me know! 

1. Just to confirm, though; even though all of the root branches are generated, we do know which branch each cell type is on, correct?

2. Will try this out. Do you think 4GB will be sufficient?

**Comment by huidongchen** [comment]
1. Yes. Different root branches are generated just for visualization. It doesn't affect the assigned branch id for each cell. (The latent tree structure is still held)

2. Sorry about it. We tested it in server, in which we have a massive amount of memory. Basically in current pipeline, the dimension reduction step is consuming a lot of memory for large data and somehow the docker image doesn't deal with it well. The worst case is that it quits without finishing. For now, i'm afraid the only workaround is to try further increase the memory. But we are working on it and will release the new version soon, in which this issue will be solved. Sorry about the inconvenience.
