### ISSUE TITLE
Error meaning? "Invalid value encountered in true_divide/greater" sc

### ISSUE THREAD

**Issue by saramasa22** [pinellolab/STREAM#58]
Dear Pinello Lab, 

I am trying to run st_detect_leaf_genes after having run the pseudotime trajectories successfully but I get this error, am I missing something in the script? 
Also when I try to get he keys after this I get pairs of numbers rather than branches

<img width="1000" alt="Screenshot 2020-01-16 at 10 30 13" src="https://user-images.githubusercontent.com/55786246/72522791-65885d80-3856-11ea-8dc2-484544d3e6ca.png">

<img width="997" alt="Screenshot 2020-01-16 at 11 41 34" src="https://user-images.githubusercontent.com/55786246/72522788-64573080-3856-11ea-892f-890ae11154a5.png">

**Comment by huidongchen** [comment]
I guess it's a bit difficult to tell based on the warning info. Can you further lower the z-score cutoff just to see if that will help get rid of the warning? 

Also I would suggest upgrading it to the latest version `v0.4.1`. Many changes have been introduced since `v0.4` (based on the output info, it looks like you are still using `v0.3`)

**Comment by saramasa22** [comment]
Thank you. 
Last curiosity, if I had a mix of cells that do not develop from the same progenitor but they come instead from completely different lineages, would the STREAM algorithm still try to join these cells together or would I see a disconnected trajectory?

**Comment by huidongchen** [comment]
Currently STREAM structure learning is based on the hypothesis that all the cells are related to each other. That being so it will learn tree or linear structure. The disconnected trajectory learning is not supported yet.
