### ISSUE TITLE
scATAC-seq using k-mers tutorial using v.0.4.1

### ISSUE THREAD

**Issue by carmenpetitjean** [pinellolab/STREAM#59]
Hi,

I am currently trying to follow the scATAC-seq using k-mers tutorial but have encountered difficulties reproducing your results (even using the same code), particularly for the dimension reduction plots and subway maps. I was wondering if these issues could be linked to the difference in STREAM versions used (your tutorial using v0.3.7 and I using v0.4.1) or if this could be due to any other reasons.

I've attached the plots that I have produced following the tutorial. 

![dimensionreductionplot1](https://user-images.githubusercontent.com/60749301/73958891-792c5e80-4900-11ea-9fe0-4d0692c3ac9b.png)
![dimensionreductionplot2](https://user-images.githubusercontent.com/60749301/73958893-79c4f500-4900-11ea-9462-6d44d27fde69.png)
![subwaymap](https://user-images.githubusercontent.com/60749301/73958903-7b8eb880-4900-11ea-826d-ad61c6e27554.png)

Thank you!

**Comment by huidongchen** [comment]
Hi ,

Thanks for trying STREAM. Indeed many changes including defaulting settings have been introduced since `v0.4`. So in order to exactly reproduce what is shown in the tutorial notebook, you might need to use the same version. 

Nevertheless, for your current analysis with `v0.4.1`, the result actually is not bad except for the monocyte population. Can you try to increase the number of clusters to get a finer initial structure e.g.`st.seed_elastic_principal_graph(adata,n_clusters=20)` or increase the number of neighbors, e.g `st.dimension_reduction(adata,n_neighbors=200)` ? This should help improve the structure learning for the disconnected part.

**Comment by carmenpetitjean** [comment]
Increasing the number of clusters and the number of neighbours seemed to have improved analysis! Thank you!
