### ISSUE TITLE
Is log transformation and normalization required here?

### ISSUE THREAD

**Issue by sylestiel** [pinellolab/STREAM#76]
Dear Huidong Chen,
I'm analyzing scATAC data. Can you comment on whether I should upload the zscores-scaled.tsv.gz or the zscores.tsv.gz (generated using the 10X cell ranger output) for the Web browser supported STREAM GUI.
In either case do i need to check Log2Transformation and Normalization radio button(s) when running the analysis.
Thank you!
SH

**Comment by huidongchen** [comment]
Hi SH,

For scATAC-seq, you should not use log2 transformation or normalization since the zscores have negative values. 

Also I would strong recommend that you check out our tutorial notebooks https://github.com/pinellolab/STREAM#tutorial. STREAM web GUI is a simplified version of STREAM package and it might not be sufficient for a solid scATAC-seq analysis.

**Comment by sylestiel** [comment]
Thank you immensely for your feedback. SHOn June 9, 2020 at 2:01 PM Huidong Chen <notifications@github.com> wrote:   Hi SH,For scATAC-seq, you should not use log2 transformation or normalization since the zscores have negative values.Also I would strong recommend that you check out our tutorial notebooks https://github.com/pinellolab/STREAM#tutorial. STREAM web GUI is a simplified version of STREAM package and it might not be sufficient for a solid scATAC-seq analysis.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
