### ISSUE TITLE
latest docker image not working

### ISSUE THREAD

**Issue by ccshao** [pinellolab/STREAM#78]
Thanks for new version. I am trying the docker image on mac, with the latest docker desktop.
First download the image `docker pull pinellolab/stream`

However, docker failed to run it.

`docker run pinellolab/stream`

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"stream\": executable file not found in $PATH": unknown.
> ERRO[0000] error waiting for container: context canceled

I am very new to docker. Are there additial steps needed before running the image? Thanks!

**Comment by huidongchen** [comment]
Hi,

As mentioned in our release note, from v1.0 we do not support command line interface anymore since a one-size-fits-all solution is not desirable. 

To use the latest version, you can:

1) (Easier version): install our bioconda package and follow our latest tutorials as before

2) (Complicated version): to use our docker image, you will have to enter docker container and mount your input data. so basically you will need to run two steps:
```
$ docker run --entrypoint /bin/bash -v /your/data/file/path/:/data -w /data -p 8888:8888 -it pinellolab/stream:1.0
```
Once you are in the container, you can start Jupyter notebook by executing:
`jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root`

**Comment by ccshao** [comment]
Thanks for the quick updates :)
