### ISSUE TITLE
Divergent and Transition Motifs

### ISSUE THREAD

**Issue by sylestiel** [pinellolab/STREAM#96]
Hi,

 1) How can we obtain Divergent and Transition Motifs  when analyzing scATAC-seq data using STREAM_scATAC-seq_motifs.ipynb in Jupyter ? 

2) For the Leaf Markers how do we intepret the data if the Z-score value is Negative. Also what does H-statistic score represent?

Thanks!

**Comment by huidongchen** [comment]
Hi,

1)You can use the same function as in scRNA-seq to detect divergent and transition motifs, e.g.
`st.detect_de_markers(adata,root='S1',cutoff_zscore=1, cutoff_logfc=0.25)` and `st.detect_transition_markers(adata,root='S1', cutoff_spearman=0.3, cutoff_logfc=0.25)`

2)The negative z-score means the marker is suppressed only on that specific branch while being expressed on the other branches. 

H-statistic score is the the Kruskal-Wallis H statistic, indicating how significant the difference between population medians is.

**Comment by sylestiel** [comment]
Thank you Huidong for your response. Just needed to clarify point 2.
So if I'm understanding you correctly a negative z-score would mean that suppression or less accessibility applies to branches with significant p-values and not the one with p-value of 1?
Thanks!

**Comment by huidongchen** [comment]
Sorry about the confusion but there are two types of p values. Here is how it works:

`H_pvalue` is associated with the Kruskal-Wallis H statistic, if `H_pvalue` <0.01, it indicates there is a significant difference between leaf branch medians but it does not tell you which branch. 

Then the post-hoc pairwise Conover’s test is applied to identify which branch has a different median. 

E.g. for a specific TF, if the p-values between a candidate leaf branch and the other leaf branches are all below a specified threshold (0.01), then this TF will be considered as leaf TF (or marker TF) of the candidate leaf branch. (since the candidate leaf branch can't be compared to itself, its pvalue will be written as 1)

That being so, the branch with pvalue 1 has different expression from the other branches. Then if zscore is negative, it means the suppression or less accessibility applies to this branch. 

It is a bit confusing but I hope the above is helpful to you.

**Comment by sylestiel** [comment]
Thanks!!
